% Generate good probes for 5 laser-low noise
clear
load SingleProbeVariables.mat %all probes
%load SingleProbeVariables_short.mat %only 1 & 2-way probes
% Single Probes
[OverallMCC_probes_LN_5l,ProbesRemoved_probes_LN_5l,ProbesRemoved_names_probes_LN_5l,Opt_Thresh_probes_LN_5l,Good_probes_probes_LN_5l,R_Cond_final_probes_LN_5l] = RemoveProbes_onebyone(probes,R_5l,low_noise,thresh,names);
% Barcodes
[OverallMCC_barcodes_LN_5l,ProbesRemoved_barcodes_LN_5l,Opt_Thresh_barcodes_LN_5l,Good_probes_barcodes_LN_5l,R_Cond_final_barcodes_LN_5l,ProbesRemoved_names_barcodes_LN_5l] = RemoveBarcodes_onebyone(Good_probes_probes_LN_5l,R_Cond_final_probes_LN_5l,low_noise,thresh,names);
% Two Barcodes
[OverallMCC_twobarcodes_LN_5l,ProbesRemoved_twobarcodes_LN_5l,Opt_Thresh_twobarcodes_LN_5l,Good_probes_twobarcodes_LN_5l,R_Cond_final_twobarcodes_LN_5l,ProbesRemoved_names_twobarcodes_LN_5l] = RemoveTwoBarcodes_onebyone(Good_probes_barcodes_LN_5l,R_Cond_final_barcodes_LN_5l,low_noise,thresh,names);
save('ProbeData_5l_LN')